**Task-1**

In [16]:
battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]

print("Battery Sensor Readings (Time (h), Temp (°C), Voltage (V), Current (A), Charge (%)):")
for data_point in battery_data:
    print(f"{data_point[0]:<16} {data_point[1]:<13} {data_point[2]:<13} {data_point[3]:<12} {data_point[4]:<12}")

print("\nTEMPERATURE AND BATTERY ALERTS")
print("--------------------------------")

for data_point in battery_data:
    time = data_point[0]
    temperature = data_point[1]
    charge = data_point[4]

    print(f"\nTime: {time} h")

    if temperature > 40:
        print("High Temperature Alert")
    else:
        print("Temperature Normal")

    if charge < 50:
        print("Low Battery Alert")
    else:
        print("Battery Charge Normal")


def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"


print("\nBATTERY STATUS")
print("--------------")

for data_point in battery_data:
    time = data_point[0]
    charge = data_point[4]
    print(f"Time: {time} h -> {battery_status(charge)}")

Battery Sensor Readings (Time (h), Temp (°C), Voltage (V), Current (A), Charge (%)):
0                32            400           20           95          
1                35            395           22           88          
2                38            390           25           80          
3                40            385           28           70          
4                42            380           30           60          
5                45            375           32           48          

TEMPERATURE AND BATTERY ALERTS
--------------------------------

Time: 0 h
Temperature Normal
Battery Charge Normal

Time: 1 h
Temperature Normal
Battery Charge Normal

Time: 2 h
Temperature Normal
Battery Charge Normal

Time: 3 h
Temperature Normal
Battery Charge Normal

Time: 4 h
High Temperature Alert
Battery Charge Normal

Time: 5 h
High Temperature Alert
Low Battery Alert

BATTERY STATUS
--------------
Time: 0 h -> High
Time: 1 h -> High
Time: 2 h -> High
Time: 3 h -> Medium
Tim

**Task-2**

In [19]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("\n\nNUMPY ANALYSIS")
print("--------------")

print("Shape of array:", D.shape)
print("Number of rows:", D.shape[0])
print("Number of columns:", D.shape[1])

average_temperature = np.mean(D[:, 0])
average_voltage = np.mean(D[:, 1])
average_current = np.mean(D[:, 2])
average_charge = np.mean(D[:, 3])

print("\nAverage Temperature:", average_temperature, "°C")
print("Average Voltage:", average_voltage, "V")
print("Average Current:", average_current, "A")
print("Average Charge:", average_charge, "%")

max_temperature = np.max(D[:, 0])
min_temperature = np.min(D[:, 0])

print("\nMaximum Temperature:", max_temperature, "°C")
print("Minimum Temperature:", min_temperature, "°C")

voltage = D[:, 1]

print("\nVoltage Column:")
print(voltage)

high_temperature = D[D[:, 0] > 40]

print("\nHigh Temperature Readings (T > 40°C):")
print(high_temperature)

low_battery = D[D[:, 3] < 50]

print("\nLow Battery Readings (C < 50%):")
print(low_battery)




NUMPY ANALYSIS
--------------
Shape of array: (6, 4)
Number of rows: 6
Number of columns: 4

Average Temperature: 38.666666666666664 °C
Average Voltage: 387.5 V
Average Current: 26.166666666666668 A
Average Charge: 73.5 %

Maximum Temperature: 45 °C
Minimum Temperature: 32 °C

Voltage Column:
[400 395 390 385 380 375]

High Temperature Readings (T > 40°C):
[[ 42 380  30  60]
 [ 45 375  32  48]]

Low Battery Readings (C < 50%):
[[ 45 375  32  48]]


**Task-3**

In [18]:
print("\n\nLINEAR ALGEBRA")
print("--------------")

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

Y = np.dot(A, X)

print("Transformation Matrix A:")
print(A)

print("\nSensor Input X:")
print(X)

print("\nTransformed Output Y = AX:")
print(Y)

A_transpose = A.T

print("\nTranspose of A:")
print(A_transpose)

det_A = np.linalg.det(A)

print("\nDeterminant of A:", det_A)

if det_A != 0:
    A_inverse = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inverse)
else:
    print("\nInverse does not exist.")

B = np.array([
    [100],
    [120]
])

solution = np.linalg.solve(A, B)

print("\nSolution of AX = B:")
print("x =", solution[0][0])
print("y =", solution[1][0])




LINEAR ALGEBRA
--------------
Transformation Matrix A:
[[2 1]
 [1 3]]

Sensor Input X:
[[40]
 [25]]

Transformed Output Y = AX:
[[105]
 [115]]

Transpose of A:
[[2 1]
 [1 3]]

Determinant of A: 5.000000000000001

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution of AX = B:
x = 36.0
y = 28.0


**Task-4**

In [17]:
print("\n\nCALCULUS ANALYSIS")
print("-----------------")

def discharge_rate(t):
    return -2 - t

rate_at_2 = discharge_rate(2)
rate_at_5 = discharge_rate(5)

print("Rate of change of charge:")
print("dC/dt = -2 - t")

print("\nDischarge rate at t = 2 hours:", rate_at_2, "% per hour")
print("Discharge rate at t = 5 hours:", rate_at_5, "% per hour")



CALCULUS ANALYSIS
-----------------
Rate of change of charge:
dC/dt = -2 - t

Discharge rate at t = 2 hours: -4 % per hour
Discharge rate at t = 5 hours: -7 % per hour


**Final Analysis and Decision**

In [11]:
print("\n\nFINAL BATTERY PERFORMANCE ANALYSIS")
print("-----------------------------------")

# Safety
for data in battery_data:
    if data[1] > 40:
        print("Temperature first exceeds 40°C at:", data[0], "hours")
        break

# Charge loss
initial_charge = battery_data[0][4]
final_charge = battery_data[-1][4]

charge_loss = initial_charge - final_charge

print("Initial Charge:", initial_charge, "%")
print("Final Charge:", final_charge, "%")
print("Total Charge Loss:", charge_loss, "%")



FINAL BATTERY PERFORMANCE ANALYSIS
-----------------------------------
Temperature first exceeds 40°C at: 4 hours
Initial Charge: 95 %
Final Charge: 48 %
Total Charge Loss: 47 %


**Final Decision**

In [12]:
print("\nFINAL DECISION:")

if max_temperature > 40 or final_charge < 50:
    print("MONITOR — The battery requires continuous monitoring.")
else:
    print("APPROVE — The battery is operating safely.")


FINAL DECISION:
MONITOR — The battery requires continuous monitoring.
